version: '3.8'

services:
  gateway:
    image: nginx:alpine
    container_name: api_gateway
    ports:
      - "80:80"   
      - "443:443" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
      - profile
      - product

  #==========================================================
  # 1 Auth Microservice
  #==========================================================
  auth:
    image: market-auth-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      #удалить при проде
      - AWS_ACCESS_KEY_ID=${AWS_ACCESSKEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRETKEY}
    build:
      context: .
      dockerfile: auth/Dockerfile
    depends_on:
      - auth_db

  auth_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD_AUTH}
    ports:
      - "${DB_PORT_AUTH}:1433"
    volumes:
      - mssql_auth_data:/var/opt/mssql

  #==========================================================
  # 2 User Microservice
  #==========================================================
  profile:
    image: market-profile-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      #удалить при проде
      - AWS_ACCESS_KEY_ID=${AWS_ACCESSKEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRETKEY}
    build:
      context: .
      dockerfile: profile/Dockerfile
    depends_on:
      - profile_db

  profile_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD_PROFILE}
    ports:
      - "${DB_PORT_PROFILE}:1433"
    volumes:
      - mssql_profile_data:/var/opt/mssql

  #==========================================================
  # 3 Product
  #==========================================================
  product:
    image: market-product-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      #удалить при проде
      - AWS_ACCESS_KEY_ID=${AWS_ACCESSKEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRETKEY}
      - AWS_BUCKET_PRODUCT=${AWS_BUCKET_PRODUCT}
    build:
      context: .
      dockerfile: Product/Dockerfile
    depends_on:
      - product_db

  product_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD_PRODUCT}
    ports:
      - "${DB_PORT_PRODUCT}:1433"
    volumes:
      - mssql_product_data:/var/opt/mssql

volumes:
  mssql_auth_data:
  mssql_profile_data:
  mssql_product_data: