events { 
    worker_connections 1024; 
}

http {
    sendfile on;

    server {
        listen 80;
        server_name localhost; 
        
        location /api/auth/ {
            proxy_pass         http://auth:80;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/profile/ {
            proxy_pass         http://profile:80;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        location /api/product/ {
            proxy_pass         http://product:80;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /swagger/auth/ {
            proxy_pass         http://auth:80/swagger/; 
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }
        
        location /swagger/profile/ {
            proxy_pass         http://profile:80/swagger/; 
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }
        
        location /swagger/product/ {
            proxy_pass         http://product:80/swagger/; 
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }
    }
}